### ISSUE TITLE
Swap from apx to apx2

### ISSUE THREAD

**Issue by CosmicFusion** [PikaOS-Linux/pikman#3]
* init should have the following option `--no-entry` because we have a GUI for managing subsystems

* Try to implement as much of you can of distrobox commands and options

* make it funtion as close to currently behavior with apx as possible for user side

* Containers
--fedora (latest fedora release)
--fedora-rawhide (fedora rawhide)
--ubuntu (Ubuntu 23.04)
--debian (Debian stable)
--debian-sid (Debian Sid)
--opensuse (OpenSUSE tumbleweed)
--clearlinux (Clear linux)
--arch (Arch Linux with paru install script)
--pika (Ubuntu 23.04 with pika-sources install script)

**Comment by ferrreo** [comment]
We are switching to apx 2 not plain distrobox, rest still pretty much applies

**Comment by CosmicFusion** [comment]
Forget to close months ago
